- hosts: all
  become: yes
  tasks:
    - name: create the 'dustin' user
      user: name=dustin append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'dustin' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'dustin ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the dustin user
      authorized_key: user=dustin key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub